name: deploy to sonatype

on: push

jobs:
  deploy:
    env:
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
    if: github.repository_owner == 'arturdm'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Deploy snapshot
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          ./gradlew \
          currentVersion \
          publishPluginMavenPublicationToSonatypeRepository
      - name: Deploy tagged release
        if: startsWith(github.ref, 'refs/tags/jacoco-android-release')
        run: |
          ./gradlew \
          currentVersion \
          publishPluginMavenPublicationToSonatypeRepository \
          closeAndReleaseSonatypeStagingRepository
